# Generated by Django 3.1.7 on 2021-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('procode', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('mnumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zipp', models.CharField(max_length=100)),
                ('pmode', models.CharField(max_length=100)),
            ],
        ),
    ]
